<?php
 
/**
 * Implementation of hook_menu().
 */

function opendata_publisher_menu() {  

  $items = array();
  
  $items['admin/content/opendata'] = array(
    'title' => 'OpenData', 
    'description' => t('General Information'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('opendata_publisher_general'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'opendata.general.inc',
  );
  
  return $items;
}
